CREATE TABLE BOOKCATEGORY(
  ID INT auto_increment PRIMARY KEY,
  NAME VARCHAR(255));

CREATE TABLE BOOK(
  ID INT auto_increment PRIMARY KEY,
  NAME VARCHAR(255),
  BOOKCATEGORYID VARCHAR(2000));

ALTER TABLE BOOK ADD FOREIGN KEY (BOOKCATEGORYID) REFERENCES BOOKCATEGORY (ID) ON UPDATE CASCADE ON DELETE CASCADE;